spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        auto-startup: true
    virtual-host: /
  profiles:
    active: dev
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
logging:
  level:
    org.springframework: DEBUG
    org.springframework.boot.actuate: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    details:
      show-details: always
